// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class InstallationStatus {
    /**
     * Creates a new InstallationStatus instance.
     * @param {Partial<InstallationStatus>} [$$source = {}] - The source object to create the InstallationStatus.
     */
    constructor($$source = {}) {
        if (!("sherpaInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sherpaInstalled"] = false;
        }
        if (!("whisperInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["whisperInstalled"] = false;
        }
        if (!("parakeetInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["parakeetInstalled"] = false;
        }
        if (!("parakeetV3Installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["parakeetV3Installed"] = false;
        }
        if (!("ffmpegInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ffmpegInstalled"] = false;
        }
        if (!("appDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallationStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallationStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallationStatus(/** @type {Partial<InstallationStatus>} */($$parsedSource));
    }
}

export class TranscriptionOptions {
    /**
     * Creates a new TranscriptionOptions instance.
     * @param {Partial<TranscriptionOptions>} [$$source = {}] - The source object to create the TranscriptionOptions.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("isFolder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFolder"] = false;
        }
        if (!("outputFormat" in $$source)) {
            /**
             * "txt", "srt", "vtt", "all"
             * @member
             * @type {string}
             */
            this["outputFormat"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * "it", "en", "es", "fr", "de", etc.
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("useCustomFolder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useCustomFolder"] = false;
        }
        if (!("customFolderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customFolderPath"] = "";
        }
        if (!("modelType" in $$source)) {
            /**
             * "whisper-tiny", "parakeet-110m" o "parakeet-v3-multi"
             * @member
             * @type {string}
             */
            this["modelType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptionOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranscriptionOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptionOptions(/** @type {Partial<TranscriptionOptions>} */($$parsedSource));
    }
}
