// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelTranscription() {
    return $Call.ByID(2260640545);
}

/**
 * @returns {$CancellablePromise<$models.InstallationStatus>}
 */
export function CheckInstallation() {
    return $Call.ByID(2907164491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadDependencies scarica sherpa-onnx e il modello specificato
 * @param {string} modelType
 * @returns {$CancellablePromise<void>}
 */
export function DownloadDependencies(modelType) {
    return $Call.ByID(1311016624, modelType);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppDir() {
    return $Call.ByID(3761896389);
}

/**
 * SelectPath apre un dialogo nativo di Windows per selezionare file o cartelle
 * @param {boolean} selectFolder
 * @returns {$CancellablePromise<string>}
 */
export function SelectPath(selectFolder) {
    return $Call.ByID(1535085674, selectFolder);
}

/**
 * Transcribe avvia la trascrizione per il file o la cartella specificata
 * @param {$models.TranscriptionOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function Transcribe(options) {
    return $Call.ByID(3620677074, options);
}

// Private type creation functions
const $$createType0 = $models.InstallationStatus.createFrom;
